name: 'Cake Action'
description: 'Run a Cake script as part of your build.'
author: 'Enrico Campidoglio'
branding:
  icon: 'box'
  color: 'yellow'
inputs:
  script-path:
    description: 'The path of the Cake script to run.'
    required: false
    default: 'build.cake'
  target:
    description: 'The name of the task to execute. Note that this argument must be supported by the script.'
    required: false
  verbosity:
    description: 'The verbosity level with which to run the script. Valid values are: Quiet, Minimal, Normal, Verbose or Diagnostic.'
    required: false
    default: 'Normal'
  cake-version:
    description: 'The version of Cake to install.'
    required: false
  cake-bootstrap:
    description: 'Flag for if Cake modules should be installed/bootstrapped.'
    required: false
    default: 'false'
  script-arguments:
    description: 'The place to pass script arguments that will be passes to runner.'
    required: false
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
